### ISSUE TITLE
Sensors setup not working

### ISSUE THREAD

**Issue by olenoerby** [GreenTurtwig/MinecraftServer-HA#1]
SO I get this when starting it up on the latest version Homeassistant:

`Error while setting up platform minecraft
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 82, in async_setup
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 400, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/sensor/minecraft.py", line 28, in setup_platform
    MCServerSensor(server, name, mcserver)
  File "/home/homeassistant/.homeassistant/custom_components/sensor/minecraft.py", line 41, in __init__
    self.update()
  File "/home/homeassistant/.homeassistant/custom_components/sensor/minecraft.py", line 56, in update
    status = self._mcserver.lookup(self._server).status()
  File "/srv/homeassistant/lib/python3.5/site-packages/mcstatus/server.py", line 49, in status
    connection = TCPSocketConnection((self.host, self.port))
  File "/srv/homeassistant/lib/python3.5/site-packages/mcstatus/protocol/connection.py", line 129, in __init__
    self.socket = socket.create_connection(addr, timeout=timeout)
  File "/usr/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused`

**Comment by filikun** [comment]
I get the same error
